PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>

CONSTRUCT {
  ?s a 
    besluit:Bestuurseenheid,
    ere:CentraalBestuurVanDeEredienst
} WHERE {
  ?s a ere:CentraalBestuurVanDeEredienst
}