
    CONSTRUCT {
      ?s a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> .
    }  
    WHERE {
      ?s a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> .
    }