
    CONSTRUCT {
      ?s a <http://lblod.data.gift/vocabularies/organisatie/OrganisatieStatusCode> .
    }  
    WHERE {
      ?s a <http://lblod.data.gift/vocabularies/organisatie/OrganisatieStatusCode> .
    }